# Generated by Django 3.1.3 on 2020-11-22 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(max_length=200, verbose_name='Назва тесту')),
                ('author', models.CharField(max_length=200, verbose_name='Автор тесту')),
                ('date', models.DateTimeField(verbose_name='Дата публікації')),
                ('testcode', models.IntegerField(null=True, verbose_name='Код тесту')),
            ],
            options={
                'verbose_name': 'Всі тести',
                'verbose_name_plural': 'Всі тести',
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcode', models.IntegerField(null=True, verbose_name='Код тесту')),
                ('ques', models.CharField(default=0, max_length=200, verbose_name='Питання')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.alltests')),
            ],
            options={
                'verbose_name': 'Питання до тесту',
                'verbose_name_plural': 'Питання до тестів',
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.IntegerField(verbose_name='Номер питання')),
                ('ans', models.CharField(default=0, max_length=200, verbose_name='Відповідь')),
                ('testcode', models.IntegerField(null=True, verbose_name='Код тесту')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.alltests')),
            ],
            options={
                'verbose_name': 'Відповідь до тесту',
                'verbose_name_plural': 'Відповіді до тестів',
            },
        ),
    ]
