# Generated by Django 3.1.3 on 2020-11-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='ques_num',
            field=models.IntegerField(null=True, verbose_name='Номер питання'),
        ),
    ]
