# Generated by Django 3.1.3 on 2020-11-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_tests_ques_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='ans',
            field=models.CharField(default=0, max_length=200, verbose_name='Відповідь'),
        ),
    ]
