# Generated by Django 3.1.3 on 2020-11-22 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_tests_ans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='question',
            new_name='ques_num',
        ),
    ]
