# Generated by Django 3.1.3 on 2020-11-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_auto_20201123_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='mark',
            field=models.IntegerField(default=0, null=True, verbose_name='Бали'),
        ),
    ]
