# Generated by Django 3.1.3 on 2020-11-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_tests_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='ans',
        ),
        migrations.AddField(
            model_name='answers',
            name='ans_value',
            field=models.CharField(default=0, max_length=200, verbose_name='Чи правильна Відповідь'),
        ),
    ]
