# Generated by Django 3.1.3 on 2020-11-28 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_auto_20201126_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests_complete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_num', models.IntegerField(null=True, verbose_name='Номер питання')),
                ('testcode', models.IntegerField(null=True, verbose_name='Код тесту')),
                ('token', models.CharField(default=0, max_length=200, verbose_name='Токен тестування')),
                ('author', models.CharField(max_length=200, verbose_name='Той хто проходить')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.alltests')),
            ],
            options={
                'verbose_name': 'Виконане питання',
                'verbose_name_plural': 'Виконані питання',
            },
        ),
        migrations.CreateModel(
            name='Answers_complete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_num', models.IntegerField(verbose_name='Номер питання')),
                ('ans', models.CharField(default=0, max_length=200, verbose_name='Відповідь того хто прозодить')),
                ('testcode', models.IntegerField(null=True, verbose_name='Код тесту')),
                ('token', models.CharField(default=0, max_length=200, verbose_name='Токен тестування')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.alltests')),
            ],
            options={
                'verbose_name': 'Відповідь до тесту',
                'verbose_name_plural': 'Відповіді до тестів',
            },
        ),
    ]
