# Generated by Django 3.1.3 on 2020-11-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_answers_complete_tests_complete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers_complete',
            options={'verbose_name': 'Введена відповідь', 'verbose_name_plural': 'Введені відповіді'},
        ),
        migrations.AddField(
            model_name='answers_complete',
            name='correct',
            field=models.CharField(default=0, max_length=200, verbose_name='Правильно?'),
        ),
    ]
