# Generated by Django 3.1.3 on 2020-11-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_auto_20201129_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltests',
            name='number_passed',
            field=models.IntegerField(default=0, null=True, verbose_name='Кількість пройдено'),
        ),
    ]
