# Generated by Django 3.1.3 on 2020-11-30 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0009_alltests_number_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='mark',
        ),
        migrations.AlterField(
            model_name='answers',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.tests'),
        ),
    ]
