# Generated by Django 3.1.3 on 2020-12-03 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0010_auto_20201201_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='ans_num',
            field=models.IntegerField(default=0, verbose_name='Номер відповіді'),
        ),
        migrations.CreateModel(
            name='Test_complete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, verbose_name='Автор тесту')),
                ('testcode', models.IntegerField(null=True, verbose_name='Код тесту')),
                ('token', models.CharField(default=0, max_length=200, verbose_name='Токен тестування')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.alltests')),
            ],
        ),
    ]
