# Generated by Django 3.1.3 on 2020-12-03 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0011_auto_20201203_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_complete',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 21, 53, 30, 765862), verbose_name='Дата проходження тесту'),
        ),
        migrations.AddField(
            model_name='tests_complete',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 21, 53, 30, 764835), verbose_name='Дата проходження тесту'),
        ),
    ]
